server:
  port: 8088

spring:
  application:
    name: MENU-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/menu_db
    username: root
    password: Amar@0112
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/